In some console environment, leftPadding is negative. Fixing below exception by adding check on leftPadding value.
C:\NuGet.exe list id:nuget.core -source "https://www.nuget.org/api/v2" -NonInteractive -Verbosity detailed
System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: totalWidth
   at System.String.PadHelper(Int32 totalWidth, Char paddingChar, Boolean isRightPadded)
   at NuGet.Common.Console.PrintJustified(Int32 startIndex, String text, Int32 maxWidth)
   at NuGet.Common.Console.PrintJustified(Int32 startIndex, String text)
   at NuGet.Commands.ListCommand.ExecuteCommand()
   at NuGet.Commands.Command.Execute()
   at NuGet.Program.Main(String[] args)